
project:

  type: website

  output-dir: docs

website:

  title: "Samuel Otterburg"

  navbar:

    right:

      - text: Home

        href: index.qmd

      - text: Projects

        href: projects.qmd

      - text: Resume

        href: resume.qmd

format:

  html:

    theme: cosmo

    css: styles.css

editor: visual



